name: Initialize Device

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: SSH to Device and Install Docker
      run: |
        # Add your SSH private key to the ssh-agent
        echo "${SSH_PRIVATE_KEY}" &
        echo "${SSH_PRIVATE_KEY}" | ssh-add - &
        ssh root@${IP_ADDRESS} "
          sudo apt-get update &&
          sudo apt-get install -y docker.io
        "
