name: Initialize Device

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH to Device and Install Docker
      run: |
        # Add your SSH private key to the ssh-agent
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 400 key.pem
        eval "$(ssh-agent -s)"
        
        ssh -v -i key.pem -o "StrictHostKeyChecking no" root@${{ secrets.IP_ADDRESS }}
#        ssh -i key.pem -o "StrictHostKeyChecking no" root@${{ secrets.IP_ADDRESS }} "
#          sudo apt-get update &&
#          sudo apt-get install -y docker.io
#        "
