name: Initialize Device

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: SSH to Device and Install Docker
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add - 
        ssh root@${{ secrets.IP_ADDRESS }} "
          sudo apt-get update &&
          sudo apt-get install -y docker.io
        "
